[general]
output-filename = "/home/greg/Downloads/Shot %b %0d %H:%M.png"
early-exit = true
corner-roundness = 8
initial-tool = "rectangle"
copy-command = "wl-copy"
annotation-size-factor = 0.5

[font]
family = "DejaVu Sans Condensed"

[color-palette]
palette = ["#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#d65d0e"]
